### ISSUE TITLE
Require Problem

### ISSUE THREAD

**Issue by azzuwan** [solisoft/arangocr#1]
I'm trying to use arangocr from a project created with crsytal init. It can't seem to find the lib. I specified the relative path like so "../lib/arangocr/src/*" then I get:
```

Error in src/welfana.cr:6: undefined constant Arango::Client (did you mean 'Range')

  client = Arango::Client.new("http://127.0.0.1:8529", "root", "Reddoor74", "welfana")
           ^~~~~~~~~~~~~~

```

**Comment by solisoft** [comment]
Please run `shards update` it will refresh the dependency ... it was missing a file ... 
Then just do : `require "arangocr"`

Here a tiny sample :

````
require "./demoarangocr/*"
require "arangocr"

module Demoarangocr
  client = Arango::Client.new("http://127.0.0.1:8529", "root", "", "demo")
  database = client.database
  puts "All Databases"
  puts database.all
end
````
Let me know if you have any issue

**Comment by azzuwan** [comment]
It works. Thanks @solisoft . Will start using it more in depth.
